version: "3.3"
services:
    warrior:
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        environment:
            DOWNLOADER: St0ner1995
            SELECTED_PROJECT: auto
            CONCURRENT_ITEMS: 6
        deploy:
            mode: replicated
            replicas: 6
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8001:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
